appointments/urls.py
from django.urls import path
from . import views
from authentication import views as authentication_views

urlpatterns = [
    path('', views.appointment, name='appointment'),
    path('my_appointments/', views.my_appointments, name='my_appointments'),
    path('book_appointment/', views.book_appointment, name='book_appointment'),
    path('unbook_appointment/', views.unbook_appointment, name='unbook_appointment'),
    path('list_all_appointments/', views.list_all_appointments, name='list_all_appointments'),
    path('list_appointments/', views.list_appointments, name='list_appointments'),
    path('my_working_days/', views.my_working_days, name='my_working_days'),
    path('vaccinated_users/', views.vaccinated_users, name='vaccinated_users'),
    path('manage_working_days/', views.manage_working_days, name='manage_working_days'),
    path('manage_appointment/', views.manage_appointment, name='manage_appointment'),
    path('analytics/', views.analytics, name='analytics'),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from users import views as user_views
from django.contrib.auth import views as auth_views
from appointments import views as appointment_views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('authentication.urls')),
    path('appointment/', include('appointments.urls')),
    path('register/', user_views.register, name='register'),
    path('profile/', user_views.profile, name='profile'),
    path('password-reset/', auth_views.PasswordResetView.as_view(template_name='users/password_reset.html'), name='password_reset'),
    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'), name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html'), name='password_reset_confirm'),
    path('password-reset-complete/', auth_views.PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'), name='password_reset_complete'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

appointments/models.py
from django.contrib.auth.models import User
from django.db import models

# Create your models here.

WEEK_DAYS = (
    (1, 'Monday'),
    (2, 'Tuesday'),
    (3, 'Wednesday'),
    (4, 'Thursday'),
    (7, 'Sunday'),
)

class Appointment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="appointments")
    time =  models.TimeField(auto_now=False, auto_now_add=False)
    day = models.IntegerField(choices=WEEK_DAYS, null=True, default=None)
    status = models.BooleanField(default=False)
    date_created = models.DateTimeField(auto_now_add=True)
    vaccinated_by = models.ForeignKey(User, on_delete=models.CASCADE, related_name="vaccinated_appointments", null=True, default=None)
    vaccinated_date = models.DateTimeField(auto_now_add=False, null=True, default=None)

    @staticmethod
    def get_appoinments_except_day(day):
        appointments = Appointment.objects.filter(status = False).exclude(day = day)
        return appointments

    @staticmethod
    def is_time_available(time, day):
        for appointment in Appointment.objects.filter(status = False, day = day):
            if appointment.time == time:
                return False
        return True

    @staticmethod
    def appointment_booked_at_time(time, day):
        for appointment in Appointment.objects.filter(status = False, day = day):
            if appointment.time == time:
                return appointment
        return False

users/models.py
from django.db import models
from django.contrib.auth.models import User
from PIL import Image
import datetime

WEEK_DAYS = (
    (1, 'Monday'),
    (2, 'Tuesday'),
    (3, 'Wednesday'),
    (4, 'Thursday'),
    (7, 'Sunday'),
)

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name="profile")
    image = models.ImageField(default='profile_pics/default.png', upload_to='profile_pics/')
    holiday = models.IntegerField(choices=WEEK_DAYS, default=7, null=True)
    confinement = models.DateTimeField(auto_now_add=False, null=True, default=None)

    def __str__(self):
        return f'{self.user.username} Profile'

    def save(self, *args, **kwargs):
        super(Profile, self).save(*args, **kwargs)

        img = Image.open(self.image.path)

        if img.height > 300 or img.width > 300:
            output_size = (300, 300)
            img.thumbnail(output_size)
            img.save(self.image.path)

    def get_image_url(self):
        try:
            return self.image.url
        except:
            return ''

    def get_appointments(self):
        try:
            return self.user.appointments.all().order_by('-date_created')
        except:
            return None

    def is_confined(self):
        if self.confinement:
            current_date = datetime.datetime.now()
            interval = datetime.timedelta(days=14).total_seconds()
            if not current_date.timestamp() - self.confinement.timestamp() > interval:
                return True
        return False

    def get_confined_end_date(self):
        if self.confinement:
            end_date = self.confinement + datetime.timedelta(days=14)
            return end_date
        return False


from .signals import *

appointments/views.py
from django.contrib import messages
from django.shortcuts import render
from users.forms import ManageHolidayForm
from django.http.response import HttpResponseForbidden
from .models import Appointment
from .models import WEEK_DAYS
from django.shortcuts import get_object_or_404, redirect, render
from users.decorators import allowed_users, user_not_confined
from django.contrib.auth.models import User
import datetime

# Create your views here.


def appointment(request):
    return render(request, 'appointments/reservation.html')

def my_appointments(request):
    return render(request, 'appointments/my-appointments.html')

@user_not_confined
def book_appointment(request):
    day = request.GET.get("day", None)
    time = request.GET.get("time", None)
    hour = time.split(":")[0]
    minute = time.split(":")[1]
    time = datetime.time(hour=int(hour), minute=int(minute))
    if Appointment.is_time_available(time, day):
        Appointment.objects.create(
            user = request.user,
            time = time,
            day = day,
        )
        messages.success(request, f"Appointment Booked Successfully For {time}.")
    else:
        messages.error(request, f"Appointment Already Booked.")
    return redirect('appointment')

def unbook_appointment(request):
    appointment_id = request.GET.get("ap_id", None)
    appointment = get_object_or_404(Appointment, id = appointment_id)
    if appointment.user == request.user:
        appointment.delete()
        messages.success(request, f"Appointment UnBooked Successfully.")
    else:
        return HttpResponseForbidden()
    return redirect('appointment')


@allowed_users(allowed_roles=['admin'])
def list_all_appointments(request):
    appointments = Appointment.objects.all().order_by('-date_created')
    context = {'appointments': appointments}
    return render(request, 'appointments/list-all-appointments.html', context)

@allowed_users(allowed_roles=['doctor'])
def list_appointments(request):
    appointments = Appointment.get_appoinments_except_day(request.user.profile.holiday).order_by('-date_created')
    context = {'appointments': appointments}
    return render(request, 'appointments/list-appointments.html', context)


@allowed_users(allowed_roles=['doctor'])
def my_working_days(request):
    working_days = []
    holidays = []
    for day in WEEK_DAYS:
        if day[0] == request.user.profile.holiday:
            holidays.append(day[1])
        else:
            working_days.append(day[1])
    context = {'working_days': working_days, 'holidays': holidays}
    return render(request, 'appointments/working-days.html', context)

@allowed_users(allowed_roles=['doctor'])
def vaccinated_users(request):
    return render(request, 'appointments/users-vaccinated.html')


@allowed_users(allowed_roles=['admin', 'doctor'])
def manage_appointment(request):
    if request.method == "POST":
        appointment_id = request.POST.get("appointment_id", None)
        action = request.POST.get("action", None)
        appointment = get_object_or_404(Appointment, id = appointment_id)
        if action == "cancel":
            appointment.delete()
            messages.success(request, "Appointment Cancelled Successfully")
        elif action == "vaccinated":
            appointment.vaccinated_by = request.user
            appointment.vaccinated_date = datetime.datetime.now()
            appointment.status = True
            appointment.save()
            messages.success(request, "Vaccinated Successfully")
        elif action == "confinement":
            appointment.user.profile.confinement = datetime.datetime.now()
            appointment.delete()
            appointment.user.profile.save()
            messages.success(request, "Confined the user, Now he can be appointed after 14 days.")
    previous_url = request.META.get('HTTP_REFERER', None)
    if previous_url:
        return redirect(previous_url)
    return redirect("Web-Home")



@allowed_users(allowed_roles=['admin'])
def manage_working_days(request):
    if request.method == "POST":
        user_id = request.POST.get("user_id", None)
        doctors = User.objects.filter(groups__name='doctor')
        user = get_object_or_404(User, id = user_id)
        form = ManageHolidayForm(request.POST)
        if form.is_valid():
            holiday = form.cleaned_data["holiday"]
            user.profile.holiday = holiday
            user.profile.save()
            messages.success(request, "Holiday updated successfully")
        context = {'doctors': doctors, 'form': form}
    if request.method == "GET":
        doctors = User.objects.filter(groups__name='doctor')
        form = ManageHolidayForm()
        context = {'doctors': doctors, 'form': form}
    return render(request, 'appointments/manage-working-days.html', context)



@allowed_users(allowed_roles=['ministry'])
def analytics(request):
    current_date = datetime.datetime.now()
    appointments = Appointment.objects.filter(status = True)
    datetime.timedelta(days=14)
    today_vaccinated = appointments.filter(vaccinated_date__day = current_date.day)
    monthly_vaccinated = appointments.filter(vaccinated_date__month = current_date.month)
    yearly_vaccinated = appointments.filter(vaccinated_date__year = current_date.year)
    previous_today_vaccinated = appointments.filter(vaccinated_date__day = current_date.day-1)
    previous_monthly_vaccinated = appointments.filter(vaccinated_date__month = current_date.month-1)
    previous_yearly_vaccinated = appointments.filter(vaccinated_date__year = current_date.year-1)
    context = {
        'today_vaccinated': today_vaccinated,
        'monthly_vaccinated': monthly_vaccinated,
        'yearly_vaccinated': yearly_vaccinated,
        'previous_today_vaccinated': previous_today_vaccinated,
        'previous_monthly_vaccinated': previous_monthly_vaccinated,
        'previous_yearly_vaccinated': previous_yearly_vaccinated,
    }
    return render(request, 'appointments/ministry-of-health.html', context)

templates/appointments/list-all-appointments.html
{% extends "base.html" %}
{% load custom_tags %}

{% block footer %}

    <section class="container">
        <h1 class="display-4 text-center mb-4">Appointments</h1>
        <div class="row" style="max-height: 80vh; overflow-y: scroll;">
            <div class="col">
                <table class="table">
                    <thead class="thead-dark">
                    <tr>
                        <th scope="col">Date Booked At</th>
                        <th scope="col">User</th>
                        <th scope="col">Time</th>
                        <th scope="col">Day</th>
                        <th scope="col">Vaccinated</th>
                        <th scope="col">Done</th>
                    </tr>
                    </thead>
                    <tbody>
                        {% for appointment in appointments %}
                        <tr>
                            <th scope="row">{{appointment.date_created.date}}</th>
                            <td>
                                <p>{{appointment.user.username|title}}</p>
                            </td>
                            <td>
                                <p>{{appointment.time}}</p>
                            </td>
                            <td>
                                <p>{{appointment.get_day_display}}</p>
                            </td>
                            <td>
                                {% if appointment.status %}
                                    <i class="fa fa-check text-success" aria-hidden="true"></i>
                                {% else %}
                                    <i class="fa fa-times text-danger" aria-hidden="true"></i>
                                {% endif %}
                            </td>
                            <td>
                                <form action="{% url 'manage_appointment' %}" method="POST">
                                    {% csrf_token %}
                                    <input type="hidden" name="appointment_id" value="{{appointment.id}}">
                                    <input type="hidden" name="action" value="cancel">
                                    <button type="submit" class="btn btn-danger btn-sm">Cancel</button>
                                </form>
                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </section>




{% endblock %}

templates/appointments/list-appointments.html
{% extends "base.html" %}
{% load custom_tags %}

{% block footer %}

    <section class="container">
        <h1 class="display-4 text-center mb-4">Appointments</h1>
        <div class="row" style="max-height: 80vh; overflow-y: scroll;">
            <div class="col">
                <table class="table">
                    <thead class="thead-dark">
                    <tr>
                        <th scope="col">Date Booked At</th>
                        <th scope="col">User</th>
                        <th scope="col">Time</th>
                        <th scope="col">Day</th>
                        <th scope="col">Vaccinated</th>
                        <th scope="col">Take Action</th>
                    </tr>
                    </thead>
                    <tbody>
                        {% for appointment in appointments %}
                        <tr>
                            <th scope="row">{{appointment.date_created.date}}</th>
                            <td>
                                <p>{{appointment.user.username|title}}</p>
                            </td>
                            <td>
                                <p>{{appointment.time}}</p>
                            </td>
                            <td>
                                <p>{{appointment.get_day_display}}</p>
                            </td>
                            <td>
                                {% if appointment.status %}
                                    <i class="fa fa-check text-success" aria-hidden="true"></i>
                                {% else %}
                                    <i class="fa fa-times text-danger" aria-hidden="true"></i>
                                {% endif %}
                            </td>
                            <td>
                                <form action="{% url 'manage_appointment' %}" method="POST" class="d-inline">
                                    {% csrf_token %}
                                    <input type="hidden" name="appointment_id" value="{{appointment.id}}">
                                    <input type="hidden" name="action" value="vaccinated">
                                    <button type="submit" class="btn btn-success btn-sm">Vaccinate</button>
                                </form>
                                <form action="{% url 'manage_appointment' %}" method="POST" class="d-inline">
                                    {% csrf_token %}
                                    <input type="hidden" name="appointment_id" value="{{appointment.id}}">
                                    <input type="hidden" name="action" value="confinement">
                                    <button type="submit" class="btn btn-danger btn-sm">Confinement</button>
                                </form>
                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </section>




{% endblock %}

templates/appointments/manage-working-days.html
{% extends "base.html" %}
{% load custom_tags %}

{% block footer %}

    <section class="container">
        <h1 class="display-4 text-center mb-4">All Doctors</h1>
        <div class="row" style="max-height: 80vh; overflow-y: scroll;">
            <div class="col">
                <table class="table">
                    <thead class="thead-dark">
                    <tr>
                        <th scope="col">Date Joined</th>
                        <th scope="col">User</th>
                        <th scope="col">Current Holiday</th>
                        <th scope="col">Change Holiday</th>
                    </tr>
                    </thead>
                    <tbody>
                        {% for doctor in doctors %}
                        <tr>
                            <th>{{doctor.date_joined.date}}</th>
                            <td>
                                <p>{{doctor.username|title}}</p>
                            </td>
                            <td>
                                <p>{{doctor.profile.get_holiday_display}}</p>
                            </td>
                            <td>
                                <form action="." method="POST">
                                    {% csrf_token %}
                                    <input type="hidden" name="user_id" value="{{doctor.id}}">
                                    {{form.holiday}}
                                    <button type="submit" class="btn btn-success btn-sm">Change</button>
                                </form>
                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </section>




{% endblock %}

templates/appointments/ministry-of-health.html
{% extends "base.html" %}

{% block content %}
    <style>
        p.title {
            border-bottom: 6px solid #9f0dc7;
            background-color: #f6f6f6;
        }

        .thumb-lg {
            height: 88px;
            width: 88px;
        }
        .profile-user-box {
            position: relative;
            border-radius: 5px
        }
        .bg-custom {
            background-color: #9f0dc7!important;
        }
        .profile-user-box {
            position: relative;
            border-radius: 5px;
        }
        
        .card-box {
            padding: 20px;
            border-radius: 10px;
            margin-bottom: 30px;
            background-color: #fff;
        }
        .inbox-widget .inbox-item img {
            width: 40px;
        }
        
        .inbox-widget .inbox-item {
            border-bottom: 1px solid #f3f6f8;
            overflow: hidden;
            padding: 10px 0;
            position: relative
        }
        
        .inbox-widget .inbox-item .inbox-item-img {
            display: block;
            float: left;
            margin-right: 15px;
            width: 40px
        }
        
        .inbox-widget .inbox-item img {
            width: 40px
        }
        
        .inbox-widget .inbox-item .inbox-item-author {
            color: #313a46;
            display: block;
            margin: 0
        }
        
        .inbox-widget .inbox-item .inbox-item-text {
            color: #98a6ad;
            display: block;
            font-size: 14px;
            margin: 0
        }
        
        .inbox-widget .inbox-item .inbox-item-date {
            color: #98a6ad;
            font-size: 11px;
            position: absolute;
            right: 7px;
            top: 12px
        }
        
        .comment-list .comment-box-item {
            position: relative
        }
        
        .comment-list .comment-box-item .commnet-item-date {
            color: #98a6ad;
            font-size: 11px;
            position: absolute;
            right: 7px;
            top: 2px
        }
        
        .comment-list .comment-box-item .commnet-item-msg {
            color: #313a46;
            display: block;
            margin: 10px 0;
            font-weight: 400;
            font-size: 15px;
            line-height: 24px
        }
        
        .comment-list .comment-box-item .commnet-item-user {
            color: #98a6ad;
            display: block;
            font-size: 14px;
            margin: 0
        }
        
        .comment-list a+a {
            margin-top: 15px;
            display: block
        }
        
        .ribbon-box .ribbon-primary {
            background: #2d7bf4;
        }
        
        .ribbon-box .ribbon {
            position: relative;
            float: left;
            clear: both;
            padding: 5px 12px 5px 12px;
            margin-left: -30px;
            margin-bottom: 15px;
            font-family: Rubik,sans-serif;
            -webkit-box-shadow: 2px 5px 10px rgba(49,58,70,.15);
            -o-box-shadow: 2px 5px 10px rgba(49,58,70,.15);
            box-shadow: 2px 5px 10px rgba(49,58,70,.15);
            color: #fff;
            font-size: 13px;
        }
        .text-custom {
            color: #02c0ce!important;
        }
        
        .badge-custom {
            background: #02c0ce;
            color: #fff;
        }
        .badge {
            font-family: Rubik,sans-serif;
            -webkit-box-shadow: 0 0 24px 0 rgba(0,0,0,.06), 0 1px 0 0 rgba(0,0,0,.02);
            box-shadow: 0 0 24px 0 rgba(0,0,0,.06), 0 1px 0 0 rgba(0,0,0,.02);
            padding: .35em .5em;
            font-weight: 500;
        }
        .text-muted {
            color: #98a6ad!important;
        }
        
        .font-13 {
            font-size: 13px!important;
        }
    </style>

    <p class="title">
        <legend>Stats of Vaccination</legend>
    </p>

    <div class="content">
        <div class="container">
            <div class="row">
                <div class="col-sm-12">
                    <!-- meta -->
                    <div class="profile-user-box card-box bg-custom">
                        <div class="row">
                            <div class="col-sm-6"><span class="float-left mr-3"><img src="{{user.profile.get_image_url}}" alt="" class="thumb-lg rounded-circle"></span>
                                <div class="media-body text-light">
                                    <h4 class="mt-1 mb-1 font-18 text-light">{{user.username|title}}</h4>
                                    <p class="font-13 text-light">Health Worker</p>

                                </div>
                            </div>
                            <div class="col-sm-6">
                                <div class="text-right">
                                    <a href="{% url 'profile' %}" class="btn btn-light waves-effect"><i class="mdi mdi-account-settings-variant mr-1"></i> Edit Profile</a>
                                </div>
                            </div>
                        </div>
                    </div>
                    <!--/ meta -->
                </div>
            </div>
            <!-- end row -->
            <div class="row">
                <div class="col-xl-12 col-12">
                    <div class="row">
                        <div class="col-sm-4">
                            <div class="card card-box tilebox-one" style="min-height: 180px;"><i class="icon-layers float-right text-muted"></i>
                                <h6 class="text-muted text-uppercase mt-0">Vaccinated Today</h6>
                                <h2 class="" data-plugin="counterup">{{today_vaccinated.count}}</h2>
                                <span class="badge badge-success">{{previous_today_vaccinated.count}}</span>
                                <span class="text-muted">Than Yesterday</span></div>
                        </div>
                        <!-- end col -->
                        <div class="col-sm-4">
                            <div class="card card-box tilebox-one" style="min-height: 180px;"><i class="icon-paypal float-right text-muted"></i>
                                <h6 class="text-muted text-uppercase mt-0">Vaccinated This Month</h6>
                                <h2 class="" data-plugin="counterup">{{monthly_vaccinated.count}}</h2>
                                <span class="badge badge-danger">{{previous_monthly_vaccinated.count}}</span>
                                <span class="text-muted">Than Last Month</span></div>
                        </div>
                        <!-- end col -->
                        <div class="col-sm-4">
                            <div class="card card-box tilebox-one" style="min-height: 180px;"><i class="icon-rocket float-right text-muted"></i>
                                <h6 class="text-muted text-uppercase mt-0">Vaccinated This Year</h6>
                                <h2 class="" data-plugin="counterup">{{yearly_vaccinated.count}}</h2>
                                <span class="badge badge-custom">{{previous_yearly_vaccinated.count}}</span>
                                <span class="text-muted">Than Last Year</span></div>
                        </div>
                        <!-- end col -->
                    </div>
                    <!-- end row -->
                </div>
                <!-- end col -->
            </div>
            <!-- end row -->
        </div>
        <!-- container -->
    </div>
{% endblock content %}

templates/appointments/my-appointments.html
{% extends "base.html" %}
{% load custom_tags %}

{% block footer %}

    <section class="container">
        <h1 class="display-4 text-center mb-4">My Appointments</h1>
        <div class="row" style="max-height: 80vh; overflow-y: scroll;">
            <div class="col">
                <table class="table">
                    <thead class="thead-dark">
                    <tr>
                        <th scope="col">Date Booked At</th>
                        <th scope="col">Time</th>
                        <th scope="col">Day</th>
                        <th scope="col">Vaccinated</th>
                    </tr>
                    </thead>
                    <tbody>
                        {% for appointment in user.profile.get_appointments %}
                        <tr>
                            <th scope="row">{{appointment.date_created.date}}</th>
                            <td>
                                <p>{{appointment.time}}</p>
                            </td>
                            <td>
                                <p>{{appointment.get_day_display}}</p>
                            </td>
                            <td>
                                {% if appointment.status %}
                                    <i class="fa fa-check text-success" aria-hidden="true"></i>
                                {% else %}
                                    <i class="fa fa-times text-danger" aria-hidden="true"></i>
                                {% endif %}
                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </section>




{% endblock %}

templates/appointments/users-vaccinated.html
{% extends "base.html" %}
{% load custom_tags %}

{% block footer %}

    <section class="container">
        <h1 class="display-4 text-center mb-4">Users You Vaccinated</h1>
        <div class="row" style="max-height: 80vh; overflow-y: scroll;">
            <div class="col">
                <table class="table">
                    <thead class="thead-dark">
                    <tr>
                        <th scope="col">Date Booked At</th>
                        <th scope="col">User</th>
                        <th scope="col">Time</th>
                        <th scope="col">Day</th>
                        <th scope="col">Vaccinated</th>
                    </tr>
                    </thead>
                    <tbody>
                        {% for appointment in user.vaccinated_appointments.all %}
                        <tr>
                            <th scope="row">{{appointment.date_created.date}}</th>
                            <td>
                                <p>{{appointment.user.username|title}}</p>
                            </td>
                            <td>
                                <p>{{appointment.time}}</p>
                            </td>
                            <td>
                                <p>{{appointment.get_day_display}}</p>
                            </td>
                            <td>
                                {% if appointment.status %}
                                    <i class="fa fa-check text-success" aria-hidden="true"></i>
                                {% else %}
                                    <i class="fa fa-times text-danger" aria-hidden="true"></i>
                                {% endif %}
                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </section>




{% endblock %}

templates/appointments/working-days.html
{% extends "base.html" %}
{% load custom_tags %}

{% block footer %}

    <section class="container">
        <div class="row">
            <div class="col-md-6">
                <h1 class="fs-2 text-center mb-4">Working Days</h1>

                <div class="row">
                    {% for day in working_days %}
                        <div class="col-12 text-center"><p class="lead border-bottom py-2 w-75 mx-auto">{{day}}</p></div>
                    {% empty %}
                        <div class="col-12 text-center"><p class="lead border-bottom py-2 w-75 mx-auto">No Working Days</p></div>
                    {% endfor %}
                </div>
            </div>
            <div class="col-md-6">
                <h1 class="fs-2 text-center mb-4">Holiday</h1>

                <div class="row">
                    {% for day in holidays %}
                        <div class="col-12 text-center"><p class="lead border-bottom py-2 w-75 mx-auto">{{day}}</p></div>
                    {% empty %}
                        <div class="col-12 text-center"><p class="lead border-bottom py-2 w-75 mx-auto">No Holidays</p></div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </section>




{% endblock %}